  apiVersion: v1
  kind: Secret
  metadata:
    name: mysql-secrets
    namespace: default
  type: Opaque
  data:
      # 인코딩 값 !db1234
    mysql-password: IWRiMTIzNA==
    mysql-root-password: IWRiMTIzNA==